# This Dockerfile is needed to create the image of whois & dig REST API.
# docker build -t wd_tg_api -f Dockerfile.api .

FROM python:3.7-slim

WORKDIR /app

COPY requirements_api.txt wd.py exceptions.py messages.py .env wd_api .

RUN pip3 install -r  /app/requirements_api.txt --no-cache-dir

RUN apt update && apt install -y dnsutils whois

CMD ["gunicorn", "wd_api.wsgi:application", "--bind", "0:8000" ]