# This Dockerfile is needed to create the image of whois & dig REST API.
# docker build -t wd_tg_api -f Dockerfile.api .

FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements_api.txt src .

RUN pip3 install --upgrade pip
RUN pip3 install -r  /app/requirements_api.txt --no-cache-dir

RUN apt update && apt install -y dnsutils whois

CMD ["uvicorn", "wd_api.main:app", "--host", "0.0.0.0", "--port", "8000"]