# This Dockerfile is needed to create the image of whois & dig telegram bot.
# docker build -t wd_tg_bot -f Dockerfile.bot .

FROM python:3.7-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements_bot.txt *.py .env .

RUN pip3 install --upgrade pip
RUN pip3 install -r  /app/requirements_bot.txt --no-cache-dir

RUN apt update && apt install -y dnsutils whois

CMD ["python3", "wd_telegram_bot.py"]