version: '3.8'
services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile.api
    restart: always
    env_file:
      - .env
  nginx:
    image: nginx:1.23.4-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
