version: '3.8'
services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile.api
    restart: always
    volumes:
      - static_value:/app/static/
    env_file:
      - .env
  nginx:
    image: nginx:1.22.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - backend

volumes:
  static_value: